#!/bin/bash

#-------------------------------------------------------------------------------
# Message Color Definitions
#-------------------------------------------------------------------------------
COLOR_NORMAL="\033[0m"
COLOR_BOLD="\033[1m"
COLOR_UNDERLINE="\033[4m"
COLOR_REVERSE="\033[7m"
COLOR_HIDDEN="\033[8m"

COLOR_BLACK="\033[30m"
COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"
COLOR_YELLOW="\033[33m"
COLOR_BLUE="\033[34m"
COLOR_VIOLET="\033[35m"
COLOR_CYAN="\033[36m"
COLOR_WHITE="\033[37m"

#-------------------------------------------------------------------------------
# Special Element Definitions
#-------------------------------------------------------------------------------
ARROW_LEFT="${COLOR_BOLD}${COLOR_YELLOW}<${COLOR_NORMAL}${COLOR_WHITE}"
ARROW_RIGHT="${COLOR_BOLD}${COLOR_YELLOW}>${COLOR_NORMAL}${COLOR_WHITE}"

BORDER_DD="${COLOR_BOLD}================================================================================${COLOR_NORMAL}"
BORDER_SD="${COLOR_BOLD}--------------------------------------------------------------------------------${COLOR_NORMAL}"
BORDER_STAR="${COLOR_BOLD}********************************************************************************${COLOR_NORMAL}"

STAR_BLUE="${COLOR_BOLD}${COLOR_BLUE}*${COLOR_NORMAL}${COLOR_WHITE}"
STAR_CYAN="${COLOR_BOLD}${COLOR_CYAN}*${COLOR_NORMAL}${COLOR_WHITE}"
STAR_GREEN="${COLOR_BOLD}${COLOR_GREEN}*${COLOR_NORMAL}${COLOR_WHITE}"
STAR_RED="${COLOR_BOLD}${COLOR_RED}*${COLOR_NORMAL}${COLOR_WHITE}"
STAR_VIOLET="${COLOR_BOLD}${COLOR_VIOLET}*${COLOR_NORMAL}${COLOR_WHITE}"
STAR_YELLOW="${COLOR_BOLD}${COLOR_YELLOW}*${COLOR_NORMAL}${COLOR_WHITE}"
